### ISSUE TITLE
How to handle dependencies?

### ISSUE THREAD

**Issue by miqueloi** [awslabs/aws-control-tower-customizations#14]
Hi,

I have been used to work with automated landing zone where there was a depends_on attribute to each cloudformation resource. I can read in the developer guide that: "The order of cloudformation_resources is used to determine the execution order for creating cloudformation_resource dependencies."
Does it mean that each stack wait for the previous to reach CREATE_COMPLETE before provisioning the next? If so it seems like a slow way to provision independent stacks.

BR Mikkel

**Comment by cgswong** [comment]
CloudFormation will actually create resources in parallel to the extent possible. But sometimes, certain resources must be created or deleted prior to another. The `DependsOn` attribute is used in cases where creation of a specific resource must follow another, and this dependency is not obvious as in the case of an implicit reference from the child (call this resource 'B') to a parent resource (call this resource 'A'. So resource A is created before B. While this serialized execution order will be slower than parallel, it is required in some cases as I have previously mentioned. For example, an EC2 instance with a public IP depends on an existing Internet Gateway attachment, so to ensure CloudFormation is aware of the dependency and executes in a consistent manner the `DependsOn` attribute is used in the EC2 instance resource to reference the IGW attachment resource.

If the resources or stacks are in fact independent of each other, the attribute should not be used and the default CloudFormation behavior used.

**Comment by miqueloi** [comment]
Thanks @cgswong! 

Sorry I probably wasn't clear enough in my questioning. I was refering to the stacksets creation coming from the manifest.yaml file. Specifically the order of which the stacks in the  cloudformation_resource gets deployed by the codepipeline. I was hoping for something like this would be an option:

```
cloudformation_resources:

  - name: EnableConfig
    template_file: templates/config.template
    parameter_file: parameters/config.template
    deploy_method: stack_set
    regions:
      - some-region-not-available-yet
    deploy_to_ou:
      - Custom

  - name: EnableConfigRules
    template_file: templates/config-rules.template
    parameter_file: parameters/config-rules.template
    deploy_method: stack_set
    regions:
      - some-region-not-available-yet
    deploy_to_ou:
      - Custom
    depends_on: 
      - EnableConfig

```
In this examble it makes sense to enable Config before adding Config rules. 
Hope it makes better sense.
