### ISSUE TITLE
SSM parameters and dependencies between stack sets

### ISSUE THREAD

**Issue by kolomied** [awslabs/aws-control-tower-customizations#32]
I may be seriously confused regarding intended scenario for `ssm_parameters` manifest property. 

My understanding is that it is supposed to help with dependencies between stack sets.  Here is a simple example with two stack sets:
* network-stack-set - deploys network resources (VPC, security groups, etc)
* app-stack-set - deploys resources that rely on VPC deployed by network-stack-set

I expect that I can save output variable from _stack instance_ in SSM parameter within Account/Region where the stack instance is deployed, so it can be consumed by different stack sets, like below:

![image](https://user-images.githubusercontent.com/55797411/93329845-bac9a400-f815-11ea-83d1-86f2fb1528ea.png)

My expectation is that I can achieve this with the following manifest:
```yaml
---
region: eu-west-1
version: 2020-01-01

cloudformation_resources:
  - name: network-stackset
    template_file: templates/network.template
    parameter_file: parameters/network.json
    ssm_parameters:
      - name: /org/member/VpcId
        value: $[output_VpcId]
    deploy_method: stack_set
    deploy_to_ou:
      - Custom
    regions:
      - eu-west-1
      - eu-central-1  
  - name: app-stackset
    template_file: templates/app.template
    parameter_file: parameters/app.json
    deploy_method: stack_set
    deploy_to_ou: 
      - Custom
    regions:
      - eu-west-1
      - eu-central-1 
```

However, what I observe is that `/org/member/VpcId` SSM parameter is created in **master** account/region - the account where the solution is deployed (the one with Control Tower enabled). No SSM parameters are created in member accounts, therefore `app-stackset` deployment fails as it relies on these parameters.

I tracked the issue down to the following lines (note that SSM client is created with default parameters, which means current - master - account and region):

https://github.com/awslabs/aws-control-tower-customizations/blob/b006bd8342ebf03b9458ec11e794ecb3bbba7845/source/state_machine_handler.py#L1010-L1016

Also, may be related to this problem - when Step Function exports CFN output variables to save them in SSM, it does so for the first Account/Region pair returned, which looks incorrect:

https://github.com/awslabs/aws-control-tower-customizations/blob/b006bd8342ebf03b9458ec11e794ecb3bbba7845/source/state_machine_handler.py#L1033-L1037

For now I have to manage SSM parameters manually within CFN templates without relying on the manifest file support. Please let me know if my understanding of the issue is correct - happy to help with PR to address it.

**Comment by kolomied** [comment]
I also tried the approach outlined in Appendix A: Using _alfred_ helper in the CloudFormation parameter files. 

I see the same issue there - parameter substitution code in `/source/manifest/cfn_params_handler.py` tries to access SSM parameters in the master account/region, not in account/region where stack instance should be deployed.

The only way that works for me is a fallback to CloudFormation default parameter values in the template (with the obvious disadvantage that I have to modify the template):

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Dev Template to test overrideparams
Parameters:
  VpcId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/org/member/VpcId'
```

In this case CloudFormation retrieves the parameters during deployment time from the region where stack instance is deployed.
